name: python-linting-code

on: push

jobs: 
  python-linting-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4  # Ensures the code is properly checked out

      # Step 2: Run Super-Linter
      - name: Super-Linter
        uses: github/super-linter@v4  # Use v4, the latest stable version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
